<?php

namespace AppBundle\Repository;

/**
 * CommerceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommerceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCommerce($tagCommerce,$tagAdresse)
    {
        $expression = '%'.$tagCommerce.'%';
        $expression2 = '%'.$tagAdresse.'%';

        $qb = $this->createQueryBuilder('a');

        $qb
            ->where($qb->expr()->like('a.nom', ':nom'))
            ->andWhere($qb->expr()->like('a.adresse', ':adresse'))
            ->setParameter('nom',$expression)
            ->setParameter('adresse',$expression2);
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
