# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    form_authenticator:
          class: AppBundle\Security\FormAuthenticator
          autowire: true

    app.pagePerso_uploader:
          class: AppBundle\FileUploader
          arguments: ['%pagePerso%']